# Generated by Django 3.1.2 on 2020-10-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=225)),
                ('content', models.TextField()),
                ('author', models.CharField(default='', max_length=225)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
