# Generated by Django 3.1.2 on 2020-10-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=225)),
                ('email', models.CharField(default='', max_length=225)),
                ('phone', models.CharField(default='', max_length=225)),
                ('content', models.TextField()),
            ],
        ),
    ]
